# Generated by Django 4.2.6 on 2023-11-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(blank=True, max_length=300, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/image_category', verbose_name='عکس دسته بندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'جزییات دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=600, unique=True, verbose_name='عنوان در url')),
                ('price1', models.IntegerField(verbose_name='قیمت')),
                ('price2', models.IntegerField(blank=True, null=True, verbose_name='قیمت بعد از تخفیف')),
                ('images', models.ImageField(blank=True, null=True, upload_to='uploads/orginal_image_product', verbose_name='تصویر اصلی محصول')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ManyToManyField(related_name='product_category', to='product_module.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'ثبت یا ویرایش محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نام رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='سایز')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images_products', verbose_name='عکس محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='product_module.product', verbose_name='محصول')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcolor', verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.size', verbose_name='سایز'),
        ),
    ]
