# Generated by Django 4.2.6 on 2023-11-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_module.productcolor', verbose_name='رنگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_module.size', verbose_name='سایز'),
            preserve_default=False,
        ),
    ]
