# Generated by Django 4.2.6 on 2023-11-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_ordercheckout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercheckout',
            options={'verbose_name': 'مشخصات کاربر', 'verbose_name_plural': 'لیست مشخصات کاربران'},
        ),
    ]
