# Generated by Django 4.2.6 on 2023-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=3000, verbose_name='سوال')),
                ('response', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='منتشر شود / نشود')),
            ],
        ),
    ]
