# Generated by Django 4.2.6 on 2023-11-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='text_header',
            field=models.TextField(blank=True, null=True, verbose_name='متن بالای صفحه'),
        ),
    ]
