# Generated by Django 4.2.6 on 2023-11-20 16:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesetting_text_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال و پاسخ', 'verbose_name_plural': 'سوالات متدوال'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_text_to_user',
            field=ckeditor.fields.RichTextField(default='', verbose_name='متن نمایش دهنده به کاربر در پروفایل'),
            preserve_default=False,
        ),
    ]
