# Generated by Django 4.2.6 on 2023-11-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_faq_options_sitesetting_show_text_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک'),
        ),
    ]
